pipeline {
    agent {
        docker {
            image 'kibatic/android-react-native:28'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh './gradlew check assemble'
            }
        }
    }
}
