version: 2
jobs:
  build:
    docker:
      - image: kibatic/android-react-native:28
    environment:
      # from https://discuss.circleci.com/t/circle-ci-v2-and-android-memory-issues/11207
      JVM_OPTS: "-Xmx1024m -XX:+PrintFlagsFinal -XX:+PrintGCDetails"
      _JAVA_OPTIONS: "-Xmx1024m"
    steps:
      - checkout
      - run: ./gradlew check -s --info
